kind: pipeline
name: default

steps:
- name: docker
  image: plugins/docker
  settings:
    username: chrispruitt
    password: 
      from_secret: docker_password
    repo: chrispruitt/jira-notifier
    tags: latest
    squash: true
    auto_tag: true
    cache_from:
      - "chrispruitt/jira-notifier:latest"